name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json  
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }} 
    - name: Install dependencies
      run: dotnet restore ApexCode.Interactive.Formatting.sln
    - name: Build
      run: dotnet build ApexCode.Interactive.Formatting.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ApexCode.Interactive.Formatting.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack ApexCode.Interactive.Formatting.sln --configuration Release --no-build -o    
    - name: Publish packages as artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: '*.nupkg'
    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
      run: dotnet nuget push **/*.nupkg --skip-duplicate --no-symbols true
